# Generated by Django 6.0 on 2025-12-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('farmer', 'Farmer')], max_length=20, null=True),
        ),
    ]
