# Generated by Django 6.0 on 2026-01-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
