# Generated by Django 6.0 on 2026-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
