# Generated by Django 6.0 on 2026-01-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0010_review_order_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
