# Generated by Django 6.0 on 2026-01-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_rename_delivery_address_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
