# Generated by Django 6.0 on 2025-12-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_type', models.CharField(choices=[('Organic', 'Organic'), ('Natural', 'Natural'), ('Mixed', 'Mixed'), ('Conventional', 'Conventional')], max_length=20)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('farm_description', models.TextField()),
                ('address', models.TextField()),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('delivers_to_home', models.BooleanField(default=True)),
                ('delivery_radius_km', models.PositiveIntegerField(default=10)),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('working_days', models.CharField(help_text='Example: Mon–Sat', max_length=100)),
                ('working_hours', models.CharField(help_text='Example: 6 AM – 6 PM', max_length=100)),
                ('government_registered', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_farmer', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='farmers/profile/')),
                ('farm_image', models.ImageField(blank=True, null=True, upload_to='farmers/farm/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
