# Generated by Django 6.0 on 2025-12-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0002_farmerprofile_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='farm_image',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='profile_image',
        ),
    ]
