# Generated by Django 6.0 on 2025-12-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0004_alter_farmerprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='village',
        ),
    ]
