# Generated by Django 6.0 on 2025-12-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0005_remove_farmerprofile_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='working_hours',
        ),
    ]
