# Generated by Django 6.0 on 2026-01-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0006_remove_farmerprofile_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
